name: Java                                  # workflow name


on: [push]

jobs:
  spotbugs:
    name: SpotBugs Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK  # If Java is not already set up
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle  # Adjust according to your build system
      run: ./gradlew build  # Use the appropriate build command for your project

    - name: Run SpotBugs
      run: ./gradlew spotbugsMain  # Use the appropriate command to run SpotBugs
      continue-on-error: true

    - name: Upload SpotBugs results
      uses: actions/upload-artifact@v2
      with:
        name: spotbugs-results
        path: build/reports/spotbugs/main.xml  # Adjust the path based on your project's configuration
      if: always()
